from tkinter import *
from tkinter import messagebox
def calcular():
  resultado = num1.get() * num2.get()
  print(resultado)
  label_resultado.config(text=f"El resultado es: {resultado}")
  messagebox.showinfo("Resultado",resultado)
ventana = Tk()
ventana.geometry("300x300")
ventana.title("Calculadora")
num1 = IntVar()
num2 = IntVar()
primer_label = Label(ventana,text="Primer numero: ")
primer_label.place(x=20,y=30)
primer_entry = Entry(ventana,textvariable=num1)
primer_entry.place(x=140,y=30)
segundo_label = Label(ventana,text="Segundo numero: ")
segundo_label.place(x=20,y=80)
segundo_entry = Entry(ventana,textvariable=num2)
segundo_entry.place(x=140,y=80)
label_resultado = Label(ventana,text="El resultado es: ")
label_resultado.place(x=20,y=150)
btn = Button(text="Calcular",command=calcular)
btn.place(x=140,y=120)
ventana.mainloop()